version: '3'

services:

  eurekaserver:
    build: ./eureka-server
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - appnetwork
  
  gateway:
   build: ./ZuulService
   image: gateway:latest
   depends_on:
     - eurekaserver
   ports:
     - "8084:8084"
   environment:
     - SPRING_APPLICATION_NAME =APIGateway
     - SPRING_PROFILES_ACTIVE=enableEureka
     - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
   networks:
     - appnetwork

  reviewmodule:
    build: ./nwt2_ms_review
    image: reviewmodule:latest
    depends_on:
      - mysql-review
      - eurekaserver
      - rabbitmq
      - gateway
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-review:3306/nwt2_review
      - SPRING_APPLICATION_NAME=nwt2_ms_review-service-client
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - appnetwork

  mysql-location:
    image: mysql:5.6
    container_name: mysql-location

    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nwt2_location
    networks:
      - appnetwork
  
  usermodule:
    build: ./nwt2_ms_identity
    image: usermodule:latest
    depends_on:
      - mysql-identity
      - eurekaserver
      - rabbitmq
      - gateway

    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-identity:3306/nwt2_identity
      - SPRING_APPLICATION_NAME =nwt2_ms_identity-service-client
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - appnetwork

  locationmodule:
    build: ./nwt2_ms_location
    image: locationmodule:latest
    depends_on:
      - mysql-location
      - eurekaserver
      - rabbitmq
      - gateway

    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-location:3306/nwt2_location
      - SPRING_APPLICATION_NAME=nwt2_ms_location-service-client
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
    networks:
      - appnetwork
  
  likemodule:
    build: ./nwt2_ms_like
    image: likemodule:latest
    depends_on:
      - mysql-like
      - eurekaserver
      - rabbitmq
      - gateway

    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-like:3306/nwt2_like
      - SPRING_APPLICATION_NAME=nwt2_ms_like-service-client
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - appnetwork

  mysql-identity:
    image: mysql:5.6
    container_name: mysql-identity
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nwt2_identity
    networks:
      - appnetwork

  mysql-review:
    image: mysql:5.6
    container_name: mysql-review
    networks:
      - appnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nwt2_review

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnetwork
  
  mysql-like:
    image: mysql:5.6
    container_name: mysql-like
    networks:
      - appnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nwt2_like

networks:
  appnetwork:
    driver: bridge
