FROM openjdk:8-jre-alpine

COPY ./target/nwt2_ms_review-0.0.1-SNAPSHOT.jar /usr/src/nwt2_ms_review/
WORKDIR /usr/src/nwt2_ms_review
EXPOSE 8083
CMD ["java", "-jar", "nwt2_ms_review-0.0.1-SNAPSHOT.jar"]


