version: '3'

services:

 eurekaserver:
  image: springio/eureka-server:latest
  ports:
   - "8761:8761"
  networks:
   - network
  environment:
   - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
   - EUREKA_CLIENT_FETCH_REGISTRY=false

 gateway:
  image: springio/zuulservice:latest
  depends_on:
   - eurekaserver
  ports:
   - "5554:8084"
  environment:
   - SPRING_APPLICATION_NAME =APIGateway
   - SPRING_PROFILES_ACTIVE=enableEureka
   - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
   - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
  networks:
   - network

 usermodule:
  image: springio/nwt2_ms_identity:latest
  depends_on:
   - mysql-identity
   - eurekaserver
   - rabbitmq
  ports:
   - "5555:8080"
  environment:
   - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-identity:3306/nwt2_identity
   - SPRING_APPLICATION_NAME =nwt2_ms_identity-service-client
   - SPRING_PROFILES_ACTIVE=enableEureka
   - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
   - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
   - SPRING_RABBITMQ_HOST=rabbitmq
  networks:
   - network


 reviewmodule:
  image: springio/nwt2_ms_review:latest
  depends_on:
   - mysql-review
   - eurekaserver
   - rabbitmq
  ports:
   - "5557:8083"
  environment:
   - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-review:3306/nwt2_review
   - SPRING_APPLICATION_NAME=nwt2_ms_review-service-client
   - SPRING_PROFILES_ACTIVE=enableEureka
   - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
   - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
   - SPRING_RABBITMQ_HOST=rabbitmq
  networks:
   - network

 rabbitmq:
  image: rabbitmq:3-management
  hostname: rabbitmq
  environment:
   - RABBITMQ_DEFAULT_USER= guest
   - RABBITMQ_DEFAULT_PASS= guest
  ports:
   - "5672:5672"
   - "15672:15672"
  networks:
   - network
  
 
 mysql-identity:
  image: mysql:5.6
  container_name: mysql-identity
  environment:
   - MYSQL_ROOT_PASSWORD=1234
   - MYSQL_DATABASE=nwt2_identity
  ports:
   - 3333:3306
  networks:
   - network

 mysql-review:
  image: mysql:5.6
  container_name: mysql-review
  ports:
   - 3307:3306
  networks:
   - network
  environment:
   - MYSQL_ROOT_PASSWORD=1234
   - MYSQL_DATABASE=nwt2_review

 
networks:
 network:
  driver: bridge