FROM openjdk:8-jre-alpine

COPY ./target/nwt2_ms_identity-0.0.1-SNAPSHOT.jar /usr/src/nwt2_ms_identity/
WORKDIR /usr/src/nwt2_ms_identity
EXPOSE 8080
CMD ["java", "-jar", "nwt2_ms_identity-0.0.1-SNAPSHOT.jar"]