FROM openjdk:8-jre-alpine

COPY ./target/nwt2_ms_location-0.0.1-SNAPSHOT.jar /usr/src/nwt2_ms_location/
WORKDIR /usr/src/nwt2_ms_location
EXPOSE 8082
CMD ["java", "-jar", "nwt2_ms_location-0.0.1-SNAPSHOT.jar"]


